<!DOCTYPE html>
<html lang="fr">

<head>
    <link rel="stylesheet" href="assets/css/gridstack.css" />
    <link rel="stylesheet" href="assets/css/gridstack-extra.css" />
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous">
        
    <link rel="stylesheet" href="assets/css/design.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <link rel="stylesheet" href="assets/css/login.css">

    <script src="assets/js/jquery-1.11.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.0/jquery-ui.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.0/lodash.min.js"></script>
    <script src="assets/js/gridstack.js"></script>
    <script src="assets/js/gridstack.jQueryUI.js"></script>
    <script src="assets/js/jszip.js"></script>  
    <script src="https://cdn.rawgit.com/eligrey/Blob.js/0cef2746414269b16834878a8abc52eb9d53e6bd/Blob.js"></script>
    <script src="https://cdn.rawgit.com/eligrey/canvas-toBlob.js/f1a01896135ab378aa5c0118eadd81da55e698d8/canvas-toBlob.js"></script>
    <script src="https://cdn.rawgit.com/eligrey/FileSaver.js/e9d941381475b5df8b7d7691013401e171014e89/FileSaver.min.js"></script>
    <title>Design</title>
</head>

<body>
    
    <?php include THEME_PATH . DS . 'navbar.phtml'; ?>

    <div class="container principale">
        <div class="row">
            <div class="col">
                <div class="ajouter">Ajouter</div>
            </div>
            <div class="col" id="barreDeMerde">
                <div class="sidebar" >
                    <div class="grid-stack-item">
                        <div class="card text-white bg-primary grid-stack-item-content base div2" data-gs-width="3" data-gs-height="3" data-color="black" style="overflow-x: hidden; overflow-y: hidden;">
                            <div class="card-header">
                                <h4>Article</h4>
                            </div>
                            <div class="card-body">
                                <input type="color" class="html5colorpicker">
                                <img src="assets/css/images/colorwheel.png" alt="color" class="color-change">

                            </div>
                            <button class="trash far fa-trash-alt"></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="save upload" id="save-grid">Generer</div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">

            <div class="ordi mx-auto">
            
                <img src="assets/css/images/ecranPC.png" alt="pc" class="center">
                <div class="ordi-ecran">
                    <div class="grid-stack ordi-ecran-navigateur grid-stack-12" id="grid1"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="barre"></div>
    </div>
    <hr/>
    <textarea id="saved-data" cols="1" rows="1" readonly="readonly"></textarea>
    

    <script type="text/javascript">
        $(function () {
            var self = this;
            var test = [];
            
            var options = {
                verticalMargin: 1,
                float: true,
                removeTimeout: 100,
                acceptWidgets: '.grid-stack-item'
            };
            $('#grid1').gridstack(options);

            var items = [
                { x: 0, y: 0, width: 12, height: 2 }
            ];

            this.saveGrid = function () {
                
                
                this.serializedData = _.map($('.grid-stack > .grid-stack-item:visible'), function (el) {
                    el = $(el);
                    var node = el.data('_gridstack_node');
                    return {
                        x: node.x,
                        y: node.y,
                        width: node.width,
                        height: node.height
                    };
                });
                var savePosition = $('#saved-data').val(JSON.stringify(this.serializedData, null, '    '));
                this.test = this.serializedData;
                var zip = new JSZip();
                var traitementcss = createCSS(this.test);
                zip.file("output.css",traitementcss);
                var traitementhtml = createHTML(this.test);
                zip.file("output.html",traitementhtml);
                var promise = null;
                zip.generateAsync({type:"blob"})
                    .then(function (blob) {
                    saveAs(blob, "output.zip");
                });
                this.test = JSON.stringify(this.test);
                //upload(this.test);
                return false;
            };

            $('#save-grid').click(this.saveGrid);

            $('.grid-stack').each(function () {
                var grid = $(this).data('gridstack');

                _.each(items, function (node) {
                    grid.addWidget($('<div class="grid-stack-item"><div class="card text-white bg-primary grid-stack-item-content base div' + 1 + '" data-color="black" data-gs-width="3" data-gs-height="3" style="overflow-x: hidden; overflow-y: hidden;"><div class="card-header"><h4>Article</h4></div><div  class="card-body"><input type="color" class="html5colorpicker"><img src="assets/css/images/colorwheel.png" alt="color" class="color-change"></div><button class="trash far fa-trash-alt"></button></div></div>'),
                        node.x, node.y, node.width, node.height);
                });
            });

            $('.sidebar .grid-stack-item').draggable({
                revert: 'invalid',
                handle: '.grid-stack-item-content',
                scroll: false,
                appendTo: 'body'
            });

            function upload(savePosition){
                $.ajax({
  method: "POST",
  url: "designajax.php",
  data: { save: savePosition }
})
  .done(function( msg ) {
    alert( "Data Saved: " + msg );
  });}

  function hexc(colorval) {
    var parts = colorval.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);
    delete(parts[0]);
    for (var i = 1; i <= 3; ++i) {
        parts[i] = parseInt(parts[i]).toString(16);
        if (parts[i].length == 1) parts[i] = '0' + parts[i];
    }
    return color = '#' + parts.join('');
}

            function download(filename, text) {
                var element = document.createElement('a');
                element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
                element.setAttribute('download', filename);

                element.style.display = 'none';
                document.body.appendChild(element);

                element.click();

                document.body.removeChild(element);
            }

            function createCSS(a) {

                var hauteur = 0;
                for (var i = 0; i < a.length; i++) {
                    if (hauteur < a[i]['y'] + a[i]['height']){
                        hauteur = a[i]['y'] + a[i]['height'];
                    }
                }

                var str = `* {
  box-sizing: border-box;
}
  
  body {
    margin: 0;
    padding: 0;
  }

.titre {
  text-align: center;
  vertical-align: middle;
}
  
  @supports not(display:grid) {
   .gridcontainer, [class^="item"] {
    display: none;
  }
    }
  
  @supports (display:grid) {
    .nogrid {
      display: none;
    }
    
    .gridcontainer {
      display: grid;
    width: 100%;
    height: 100%;
    justify-content: center;
    align-content: center;
    grid-template-columns: repeat(12, 8.3%);
    grid-template-rows: repeat(` + hauteur + `, 12vmin);
  }
    
`;

                for (var i = 0; i < a.length; i++) {
                    var color = $('.div'+(i+1)).css('backgroundColor');
                    var hexaValue = hexc(color);
                    var x = "";
                    var separatorX = "";
                    var y = "";
                    var separatorY = "";
                    if (a[i]['width'] > 1){
                        x = a[i]['x'] + a[i]['width'] + 1;
                        separatorX = " / ";
                    }
                    if (a[i]['height'] > 1){
                        y = a[i]['y'] + a[i]['height'] + 1;
                        separatorY = " / ";
                    }
                    str += ` .item` + (i+1) + ` {
    background-color: ` + hexaValue  + `;
    grid-column: ` + (a[i]['x']+1) + separatorX + x +`;
    grid-row: ` + (a[i]['y']+1) + separatorY + y +`;
    margin: 1px;
  }

`;
                }
                str += `}`;
                return str;
            }

function createHTML(a) {
    var str = `<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="output.css">
    <title>Test affichage</title>
</head>

<body>
    <div class="gridcontainer">
`;

    for (var i = 0; i < a.length; i++) {
        var titreDiv = $('.div'+(i+1)).find('h4').text();
         str +=`        <div class="item` + (i+1) + `"><h2 class="titre">` + titreDiv + `</h2></div>
         `;
        }
        str += `
    </div>
</body>

</html>`;
    return str;
}


        });
    </script>
    <script src="assets/js/index.js"></script>/>
</body>
</html>