<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/login.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <title>Login</title>
</head>

<body class="loginPage">
    
    <?php include THEME_PATH . DS . 'navbar.phtml'; ?>
    
    <div class="login">
        <div class="container">
            <div class="inner-login">

                <div class="col-lg-6 col-lg-offset-3">
                    <div class="login-box">
                    <?php if(!empty($errors)): ?>
                        <div class="alert alert-danger">
                            <ul>
                                <?php foreach ($errors as $err): ?>
                                <li><?= $err ; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                        <form method="POST">
                            <h1>Login</h1>
                            <div class="form-group">
                                <div class="col-lg-1 icone">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                </div>
                                <div class="col-lg-11">
                                    <input id="username" placeholder="Username" type="text" class="form-control" name="username" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-1 icone">
                                    <i class="fa fa-key" aria-hidden="true"></i>
                                </div>
                                <div class="col-lg-11">
                                    <input id="password" placeholder="Password" type="password" class="form-control" name="password" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="buttons">
                                    <button class="btn btn-danger btn-cancel">Cancel</button>
                                    <input type="submit" class="btn btn-success btn-login" value="Login" />
                                </div>
                                Not a Member ?
                                <a href="<?= BASE_URL; ?>/signup.php">Signup</a>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <script src="assets/js/jquery-1.11.1.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
</body>

</html>