<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/login.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous">
    <title>Signup</title>
</head>

<body class="loginPage">
    
    <?php include THEME_PATH . DS . 'navbar.phtml'; ?>
    
    <div class="login">
        <div class="container">
            <div class="inner-login">

                <div class="col-lg-6 col-lg-offset-3">
                    <div class="signup-box">
                    <?php if(!empty($errors)): ?>
                        <div class="alert alert-danger">
                            <ul>
                                <?php foreach ($errors as $err): ?>
                                <li><?= $err ; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <?php if(!empty($username)): ?>
                        <div class="alert alert-danger">
                            <ul>
                                <li><?=$username ?></li>
                                <li><?=$password ?></li>
                                <li><?=$verifpass ?></li>
                                <li><?=$email ?></li>
                            </ul>
                        </div>
                    <?php endif; ?>

                        <form  method="POST">
                            <h1>Signup</h1>
                            <div class="form-group">
                                <div class="col-lg-1 icone">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                </div>
                                <div class="col-lg-11">
                                    <input id="username" placeholder="Username" type="text" class="form-control"  name="username" value="<?= $username ?>" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-1 icone">
                                    <i class="fas fa-envelope" aria-hidden="true"></i>
                                </div>
                                <div class="col-lg-11">
                                    <input id="email" placeholder="Email" type="email" class="form-control" name="email" value="<?= $email ?>" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-1 icone">
                                    <i class="fas fa-envelope" aria-hidden="true"></i>
                                </div>
                                <div class="col-lg-11">
                                    <input id="confirmEmail" placeholder="Confirm Email" type="email" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-1 icone">
                                    <i class="fa fa-key" aria-hidden="true"></i>
                                </div>
                                <div class="col-lg-11">
                                    <input id="password" placeholder="Password" type="password" class="form-control" name="password" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-1 icone">
                                    <i class="fa fa-key" aria-hidden="true"></i>
                                </div>
                                <div class="col-lg-11">
                                    <input id="repeatpass" name="repeatpass" placeholder="Confirm Password" type="password" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="buttons">
                                    <button class="btn btn-danger btn-cancel">Cancel</button>
                                    <input type="submit" class="btn btn-success btn-login" value="Login" />
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <script src="assets/js/jquery-1.11.1.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
</body>

</html>